# 빌드 단계
FROM node:20.16.0 as builder
WORKDIR /app
COPY hystech-front/package.json hystech-front/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY hystech-front/ .
EXPOSE 3000
CMD ["yarn", "start"]

# # 배포 단계
# FROM nginx:1.26.1
# COPY --from=builder /app/build /usr/share/nginx/html
# COPY hystech-front/nginx.conf /etc/nginx/conf.d/default.conf


# CMD ["nginx", "-g", "daemon off;"]