version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - 3000:80
    volumes:
      - ./hystech-front:/app
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastAPI
    ports:
      - 8000:8000
    volumes:
      - ./hystech-backend:/app
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    volumes:
      - ./hystech-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  hystech-data: